### ISSUE TITLE
Watermarks in photos ?

### ISSUE THREAD

**Issue by Cmejia** [500px/api-documentation#128]
Just got a report today from one of our app users that the 500px photos are showing up with a text watermark stating their web url. This happens on our app. It does not happen  on the website, or the official app.  Just checked. 

Is this intentional ?

**Comment by cdmicacc** [comment]
Yes, this is a recent change in our API.  Please see our [documentation on images](https://github.com/500px/api-documentation/blob/master/basics/formats_and_terms.md#image-urls-and-image-sizes) for more details.

**Comment by vachi** [comment]
beat me to it :)

**Comment by Cmejia** [comment]
Mm. We've been users of the api since day 1. I understand the reasoning. 
1) sending an email to sales. We don't make that much money to the app but we want to keep the users happy
2) on that note could it be possible to not watermark your own photos if the request to get the photos is properly signed authenticated?
If I want one show case my own photos on my Apple TV (something our app does well) I don't want the watermark. For 3rd party photos I understand it......

**Comment by Cmejia** [comment]
What I mean can Photostackr get an exception ? --- or can now we allow users to download photos to their iOS photo library, given they are watermarked ? (We currently don't allow it)

**Comment by vachi** [comment]
like you said, contact sales

**Comment by cdmicacc** [comment]
This has been fixed -- if you access an API as an authenticated user you will not get watermarked images when retrieving that users' own photos.

**Comment by Cmejia** [comment]
Hi Chris, has this been deployed to production ?

This request (signed with OAuth), keeps returning photo URLs that show a watermark... (where user_id is the current user)

https://api.500px.com/v1/photos?sort=created_at&rpp=60&image_size%5B%5D=1&image_size%5B%5D=2&image_size%5B%5D=3&image_size%5B%5D=4&image_size%5B%5D=5&include_states=1&user_id=165441&page=1&feature=user

**Comment by cdmicacc** [comment]
Hmm, thanks for the info -- what you're seeing is definitely a bug. I've added it to our list of issues and I'll update this ticket when the fix is deployed.

**Comment by cdmicacc** [comment]
This issue should now be resolved.  Please let me know if you still have any problems.

**Comment by Cmejia** [comment]
Yes it has :) -- thank you very much, our app users will be very happy [they care on the watermark on their own photos]

**Comment by karevn** [comment]
It looks like the same issue exists for collections - when my application tries to pull user's collection from /collections/:id with an authenticated request, it still receives watermarked photos.

**Comment by karevn** [comment]
@cdmicacc Can you please answer?

**Comment by mattjiggins** [comment]
@cdmicacc this problem still seems to exist for collections - any progress on this?

**Comment by pmpinto** [comment]
Same problem here with collections. It would be nice to have my own photos on my own website with no watermarks.
Still no galleries request available?

**Comment by pmpinto** [comment]
@cdmicacc Hi Chris! Could you please take a look at my previous post? Am I expecting something that is not expectable?

**Comment by PAk-CatchFire** [comment]
Any solution to this?

**Comment by pmpinto** [comment]
@PAk-CatchFire Ended up not using it but check if this helps: https://github.com/500px/api-documentation/issues/184#issuecomment-192951351
